// import jsPDF from "jspdf";
// import { AnalysisResult } from "@/lib/types";

// export const generateAndDownloadReport = (
//   r: AnalysisResult,
//   submittedBy: string
// ) => {
//   const pdf = new jsPDF();
//   let y = 10;
//   const pageHeight = pdf.internal.pageSize.height;

//   const line = (text: string) => {
//     if (y > pageHeight - 10) {
//       pdf.addPage();
//       y = 10;
//     }
//     pdf.text(text, 10, y);
//     y += 8;
//   };

//   line("PLAGIARISM ANALYSIS REPORT");
//   line("--------------------------------");
//   line(`File Name   : ${r.file_name}`);
//   line(`Document ID: ${r.document_id}`);
//   line(`Submitted By: ${submittedBy}`);
//   line(`Date        : ${new Date(r.analysis_date).toLocaleString()}`);
//   line("");

//   line("RESULT SUMMARY");
//   line("--------------------------------");
//   line(`AI Generated Content       : ${r.ai_detected_percentage}%`);
//   line(`Similarity to Web Sources : ${r.web_source_percentage}%`);
//   line(`Likely Original Content   : ${r.human_written_percentage}%`);
//   line("");

//   if (r.matched_sources?.length) {
//     line("MATCHED SOURCES");
//     line("--------------------------------");

//     r.matched_sources.forEach((src, i) => {
//       if (src.type === "web") {
//         pdf.setTextColor(0, 0, 255);
//         pdf.textWithLink(`${i + 1}. ${src.source}`, 10, y, { url: src.source });
//         y += 8;
//         pdf.setTextColor(0, 0, 0);
//       } else {
//         line(`${i + 1}. Internal Database Match (${src.source})`);
//       }
//     });
//   }

//   line("");
//   line("Generated by TKREC Plagiarism Analysis System");

//   pdf.save(`${r.document_id}-analysis-report.pdf`);
// };




// // reportGenerator.tsx

// export function generateAndDownloadReport(data: any) {
//   const {
//     file_name,
//     document_id,
//     submitted_by,
//     analysis_date,
//     ai_detected_percentage,
//     web_source_percentage,
//     human_written_percentage,
//     matched_sources = [],
//   } = data;

//   const METHODOLOGY_TEXT = `
// METHODOLOGY
// -----------
// This plagiarism analysis uses a hybrid approach combining:
// 1. AI-generated content detection using transformer-based language models.
// 2. Web similarity detection using publicly indexed web sources.
// 3. Local database comparison against previously submitted documents.

// The system computes similarity scores based on text overlap patterns,
// semantic similarity, and statistical language features.

// AI DETECTION LIMITATIONS
// -----------------------
// • AI detection is probabilistic, not deterministic.
// • High AI percentage does NOT guarantee the content was generated by AI.
// • Human-written text may exhibit AI-like patterns.
// • AI and web similarity scores may overlap.

// ACADEMIC DISCLAIMER
// -------------------
// • Similarity percentages are indicators, not accusations.
// • This report is intended for academic and educational use only.
// • Final decisions should involve human review and institutional guidelines.
// `;

//   const sourcesText =
//     matched_sources.length > 0
//       ? matched_sources.map((s: any) => `• ${s}`).join("\n")
//       : "No external sources detected.";

//   return `
// PLAGIARISM ANALYSIS REPORT
// -------------------------
// File Name : ${file_name}
// Document ID : ${document_id}
// Submitted By : ${submitted_by}
// Date : ${analysis_date}

// RESULT SUMMARY
// --------------
// AI Generated Content : ${ai_detected_percentage}%
// Similarity to Web Sources : ${web_source_percentage}%
// Likely Original Content : ${human_written_percentage}%

// ${METHODOLOGY_TEXT}

// MATCHED SOURCES
// ---------------
// ${sourcesText}

// NOTE
// ----
// • Web links are clickable and shown in blue.
// • Local database references indicate internal document matches.
// • Percentages may overlap and should be interpreted carefully.
// • Generated by TKREC Plagiarism Analysis System.
// `;
// }





// // src/lib/reportGenerator.tsx
// import jsPDF from "jspdf";
// import { AnalysisResult } from "@/lib/types";

// export function generateAndDownloadReport(
//   result: AnalysisResult,
//   submittedBy: string
// ) {
//   const pdf = new jsPDF();
//   let y = 10;
//   const pageHeight = pdf.internal.pageSize.height;

//   const line = (text: string) => {
//     if (y > pageHeight - 10) {
//       pdf.addPage();
//       y = 10;
//     }
//     pdf.text(text, 10, y);
//     y += 8;
//   };

//   line("PLAGIARISM ANALYSIS REPORT");
//   line("--------------------------------");
//   line(`Document ID    : ${result.document_id}`);
//   line(`Submitted By   : ${submittedBy}`);
//   line(`Date           : ${new Date(result.analysis_date).toLocaleString()}`);
//   line("");

//   line("RESULT SUMMARY");
//   line("--------------------------------");
//   line(`AI Generated Content        : ${result.ai_detected_percentage}%`);
//   line(`Similarity to Web Sources  : ${result.web_source_percentage}%`);
//   line(`Likely Original Content    : ${result.human_written_percentage}%`);
//   line("");

//   line("METHODOLOGY");
//   line("--------------------------------");
//   line("• AI detection using transformer-based models");
//   line("• Web similarity via indexed public sources");
//   line("• Local database comparison");
//   line("");

//   line("LIMITATIONS & DISCLAIMER");
//   line("--------------------------------");
//   line("• AI detection is probabilistic, not deterministic");
//   line("• Similarity scores are indicators, not accusations");
//   line("• Final decisions require human review");
//   line("");

//   if (result.matched_sources?.length) {
//     line("MATCHED SOURCES");
//     line("--------------------------------");
//     result.matched_sources.forEach((src, i) => {
//       if (src.type === "web") {
//         pdf.setTextColor(0, 0, 255);
//         pdf.textWithLink(`${i + 1}. ${src.source}`, 10, y, { url: src.source });
//         pdf.setTextColor(0, 0, 0);
//         y += 8;
//       } else {
//         line(`${i + 1}. Internal DB Match (${src.source})`);
//       }
//     });
//   }

//   pdf.save(`${result.document_id}-analysis-report.pdf`);
// }












// // src/lib/reportGenerator.tsx
// import jsPDF from "jspdf";
// import { AnalysisResult } from "@/lib/types";

// type MatchedSource = {
//   type: "web" | "local_db";
//   source: string;
// };

// export function generateAndDownloadReport(
//   r: AnalysisResult,
//   submittedBy: string
// ) {
//   const pdf = new jsPDF("p", "mm", "a4");

//   const marginX = 20;
//   const lineHeight = 7;
//   const pageHeight = pdf.internal.pageSize.height;
//   const pageWidth = pdf.internal.pageSize.width;

//   let y = 25;

//   const addPageIfNeeded = () => {
//     if (y > pageHeight - 20) {
//       pdf.addPage();
//       y = 25;
//     }
//   };

//   const sectionTitle = (text: string) => {
//     addPageIfNeeded();
//     pdf.setFont("helvetica", "bold");
//     pdf.setFontSize(13);
//     pdf.text(text, marginX, y);
//     y += lineHeight;
//     pdf.line(marginX, y, pageWidth - marginX, y);
//     y += lineHeight;
//     pdf.setFont("helvetica", "normal");
//     pdf.setFontSize(11);
//   };

//   const textBlock = (text: string) => {
//     const wrapped = pdf.splitTextToSize(text, pageWidth - marginX * 2);
//     wrapped.forEach((line: string) => {
//       addPageIfNeeded();
//       pdf.text(line, marginX, y);
//       y += lineHeight;
//     });
//   };

//   const linkBlock = (url: string, index: number) => {
//     const wrapped = pdf.splitTextToSize(
//       `${index}. ${url}`,
//       pageWidth - marginX * 2
//     );

//     wrapped.forEach((line: string, i: number) => {
//       addPageIfNeeded();
//       if (i === 0) {
//         pdf.setTextColor(0, 0, 200);
//         pdf.textWithLink(line, marginX, y, { url });
//         pdf.setTextColor(0, 0, 0);
//       } else {
//         pdf.text(line, marginX + 5, y);
//       }
//       y += lineHeight;
//     });
//   };

//   /* ================= HEADER ================= */
//   pdf.setFont("helvetica", "bold");
//   pdf.setFontSize(16);
//   pdf.text("PLAGIARISM ANALYSIS REPORT", pageWidth / 2, 15, { align: "center" });

//   pdf.setFont("helvetica", "normal");
//   pdf.setFontSize(11);

//   textBlock(`File Name      : ${r.file_name}`);
//   textBlock(`Document ID    : ${r.document_id}`);
//   textBlock(`Submitted By   : ${submittedBy}`);
//   textBlock(`Date           : ${new Date(r.analysis_date).toLocaleString()}`);

//   /* ================= SUMMARY ================= */
//   sectionTitle("RESULT SUMMARY");
//   textBlock(`AI Generated Content        : ${r.ai_detected_percentage}%`);
//   textBlock(`Similarity to Web Sources  : ${r.web_source_percentage}%`);
//   textBlock(`Likely Original Content    : ${r.human_written_percentage}%`);

//   /* ================= METHODOLOGY ================= */
//   sectionTitle("METHODOLOGY");
//   textBlock("• AI detection using transformer-based transformer models");
//   textBlock("• Web similarity via indexed public sources (Google CSE)");
//   textBlock("• Local institutional database comparison");

//   /* ================= LIMITATIONS ================= */
//   sectionTitle("LIMITATIONS & DISCLAIMER");
//   textBlock("• AI detection is probabilistic, not deterministic");
//   textBlock("• Similarity percentages are indicators, not accusations");
//   textBlock("• Final academic decisions require human review");

//   /* ================= SOURCES ================= */
//   if (r.matched_sources?.length) {
//     sectionTitle("MATCHED SOURCES");

//     (r.matched_sources as MatchedSource[]).forEach((src, i) => {
//       if (src.type === "web") {
//         linkBlock(src.source, i + 1);
//       } else {
//         textBlock(`${i + 1}. Internal Database Match (${src.source})`);
//       }
//     });
//   }

//   /* ================= FOOTER ================= */
//   pdf.setFontSize(9);
//   pdf.setTextColor(120);
//   pdf.text(
//     "Generated by TKREC Plagiarism Analysis System — Academic Use Only",
//     pageWidth / 2,
//     pageHeight - 10,
//     { align: "center" }
//   );

//   const safeName = submittedBy.replace(/\s+/g, "_").toLowerCase();
//   pdf.save(`${safeName}-plagiarism-report.pdf`);
// }









import jsPDF from "jspdf";
import type { AnalysisResult, MatchedSource } from "@/lib/types";

/* =========================================================
   PUBLIC API
========================================================= */
export function generateAndDownloadReport(
  r: AnalysisResult,
  submittedBy: string,
  originalFileName?: string
) {
  const pdf = new jsPDF("p", "mm", "a4");

  const marginX = 20;
  const lineHeight = 7;
  const pageHeight = pdf.internal.pageSize.height;
  const pageWidth = pdf.internal.pageSize.width;

  let y = 25;

  /* ================= UTILITIES ================= */
  const addPageIfNeeded = () => {
    if (y > pageHeight - 20) {
      pdf.addPage();
      y = 25;
    }
  };

  const sectionTitle = (text: string) => {
    y += 6;
    addPageIfNeeded();
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(13);
    pdf.text(text, marginX, y);
    y += 4;
    pdf.setDrawColor(180);
    pdf.line(marginX, y, pageWidth - marginX, y);
    y += lineHeight;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);
  };

  const textBlock = (text: string) => {
    const wrapped = pdf.splitTextToSize(text, pageWidth - marginX * 2);
    wrapped.forEach((line: string) => {
      addPageIfNeeded();
      pdf.text(line, marginX, y);
      y += lineHeight;
    });
  };

  // const linkBlock = (url: string, index: number) => {
  //   const wrapped = pdf.splitTextToSize(
  //     `${index}. ${url}`,
  //     pageWidth - marginX * 2
  //   );

  //   wrapped.forEach((line: string, i: number) => {
  //     addPageIfNeeded();
  //     if (i === 0) {
  //       pdf.setTextColor(0, 0, 200);
  //       pdf.textWithLink(line, marginX, y, { url });
  //       pdf.setTextColor(0, 0, 0);
  //     } else {
  //       pdf.text(line, marginX + 5, y);
  //     }
  //     y += lineHeight;
  //   });
  // };
  const linkBlock = (url: string, index: number) => {
  addPageIfNeeded();

  // Reference number
  pdf.setFont("helvetica", "bold");
  pdf.text(`[${index}]`, marginX, y);
  pdf.setFont("helvetica", "normal");
  y += lineHeight;

  const wrapped = pdf.splitTextToSize(
    url,
    pageWidth - marginX * 2 - 5
  );

  wrapped.forEach((line: string, i: number) => {
    addPageIfNeeded();

    if (i === 0) {
      // Only FIRST line is clickable (jsPDF limitation)
      pdf.setTextColor(0, 0, 200);
      pdf.textWithLink(line, marginX + 5, y, { url });
      pdf.setTextColor(0, 0, 0);
    } else {
      // Continuation lines (visual only)
      pdf.text(line, marginX + 5, y);
    }

    y += lineHeight;
  });

  y += lineHeight * 0.5;
};



  /* ================= HEADER ================= */
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(16);
  pdf.text("PLAGIARISM ANALYSIS REPORT", pageWidth / 2, 15, { align: "center" });

  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");

  textBlock(`File Name      : ${originalFileName ?? "N/A"}`);
  textBlock(`Document ID    : ${r.document_id}`);
  textBlock(`Submitted By   : ${submittedBy}`);
  textBlock(`Date           : ${new Date(r.analysis_date).toLocaleString()}`);

  /* ================= SUMMARY ================= */
  sectionTitle("RESULT SUMMARY");
  textBlock(`AI Generated Content        : ${r.ai_detected_percentage}%`);
  textBlock(`Similarity to Web Sources  : ${r.web_source_percentage}%`);
  textBlock(`Likely Original Content    : ${r.human_written_percentage}%`);

  /* ================= METHODOLOGY ================= */
  sectionTitle("METHODOLOGY");
  textBlock("• AI detection using transformer-based models");
  textBlock("• Web similarity via indexed public sources (Google CSE)");
  textBlock("• Local institutional database comparison");

  /* ================= LIMITATIONS ================= */
  sectionTitle("LIMITATIONS & DISCLAIMER");
  textBlock("• AI detection is probabilistic, not deterministic");
  textBlock("• Similarity percentages are indicators, not accusations");
  textBlock("• Final academic decisions require human review");

  /* ================= SOURCES ================= */
  if (r.matched_sources?.length) {
    sectionTitle("MATCHED SOURCES");
    r.matched_sources.forEach((src: MatchedSource, i: number) => {
      if (src.type === "web") {
        linkBlock(src.source, i + 1);
      } else {
        textBlock(`${i + 1}. Internal Database Match (${src.source})`);
      }
    });
  }

  /* ================= FOOTER ================= */
  pdf.setFontSize(9);
  pdf.setTextColor(120);
  pdf.text(
    "Generated by TKREC Plagiarism Analysis System — Academic Use Only",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  /* ================= FILE NAME ================= */
  const safeUser = submittedBy.replace(/\s+/g, "_").toLowerCase();
  pdf.save(`${safeUser}-plagiarism-report.pdf`);
}
